version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    links:
      - postgres
    environment:
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=joe
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=password
